server {
    listen 80;
    listen [::]:80;
    server_name cp.vidanoff.ru;

    # Optional but recommended: redirect HTTP to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 8443 ssl http2;
    listen [::]:8443 ssl http2;
    server_name cp.vidanoff.ru;

    ssl_certificate     /etc/letsencrypt/live/cp.vidanoff.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cp.vidanoff.ru/privkey.pem;

    client_max_body_size 5m;

    location / {
        proxy_pass http://127.0.0.1:3017;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

